const products = [
  {
    id: 1,
    skun: '1872621',
    name: 'Skate',
    image: '/images/card_images/skate_1.png',
    description:
      'Forget about those wooden limos and pick yourself up the Polar Boserio Limo Deck 8.25 x 31.875. This is a pro quality skateboard deck constructed from traditional 7-ply maple wood with background stains that could be different. FREE griptape is available with the purchase of the deck',
    brand: 'Polar',
    size: 8.5,
    category: 'street',
    price: 99.9,
    stock: 2,
    rating: 1.4,
    numReviews: 12,
  },
  {
    id: 2,
    skun: '1872622',
    name: 'Surf',
    image: '/images/card_images/softboard-9-verde-azul.png',
    description:
      'Forget about those wooden limos and pick yourself up the Polar Boserio Limo Deck 8.25 x 31.875. This is a pro quality skateboard deck constructed from traditional 7-ply maple wood with background stains that could be different. FREE griptape is available with the purchase of the deck',
    brand: 'Anty-Hero',
    category: 'beach',
    price: 90,
    stock: 3,
    rating: 4.5,
    numReviews: 45,
  },
  {
    id: 3,
    skun: '1872623',
    name: 'Bike',
    image: '/images/card_images/rossignol_snowboard.png',
    description:
      'Forget about those wooden limos and pick yourself up the Polar Boserio Limo Deck 8.25 x 31.875. This is a pro quality skateboard deck constructed from traditional 7-ply maple wood with background stains that could be different. FREE griptape is available with the purchase of the deck',
    brand: 'Polar',
    category: 'street',
    price: 350,
    stock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    id: 4,
    skun: '1872624',
    name: 'Sky',
    image: '/images/card_images/salvador-park.png',
    description:
      'Forget about those wooden limos and pick yourself up the Polar Boserio Limo Deck 8.25 x 31.875. This is a pro quality skateboard deck constructed from traditional 7-ply maple wood with background stains that could be different. FREE griptape is available with the purchase of the deck',
    brand: 'Polar',
    category: 'snow',
    price: 300,
    stock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    id: 5,
    skun: '1872625',
    name: 'Scooter',
    image: '/images/card_images/scooter.png',
    description:
      'Forget about those wooden limos and pick yourself up the Polar Boserio Limo Deck 8.25 x 31.875. This is a pro quality skateboard deck constructed from traditional 7-ply maple wood with background stains that could be different. FREE griptape is available with the purchase of the deck',
    brand: 'Polar',
    category: 'Skate',
    price: 89.99,
    stock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    id: 6,
    skun: '1872626',
    name: 'Treking shoe',
    image: '/images/card_images/treking.png',
    description:
      'Forget about those wooden limos and pick yourself up the Polar Boserio Limo Deck 8.25 x 31.875. This is a pro quality skateboard deck constructed from traditional 7-ply maple wood with background stains that could be different. FREE griptape is available with the purchase of the deck',
    brand: 'Polar',
    category: 'beach',
    price: 89.99,
    stock: 10,
    rating: 4.5,
    numReviews: 12,
  },
];

export default products;
