export const ORDER_LINE_BY_ID = 'ORDER_LINE_BY_ID';
export const ORDER_LINE_BY_ID_SUCCESS = 'ORDER_LINE_BY_ID_SUCCESS';
export const ORDER_LINE_BY_ID_ERROR = 'ORDER_LINE_BY_ID_ERROR';

export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_ERROR = 'ADD_ORDER_ERROR';

export const REMOVE_ORDER_LINE_BY_ID = 'REMOVE_ORDER_LINE_BY_ID';
export const REMOVE_ORDER_LINE_SUCCESS = 'REMOVE_ORDER_LINE_SUCCESS';
export const REMOVE_ORDER_LINE_ERROR = 'REMOVE_ORDER_LINE_ERROR';

export const CHANGE_QUANTITY_PRODUCT_LINE = 'CHANGE_QUANTITY_PRODUCT_LINE';
export const CHANGE_QUANTITY_PRODUCT_LINE_SUCCESS =
  'CHANGE_QUANTITY_PRODUCT_LINE_SUCCESS';

export const CHANGE_QUANTITY_PRODUCT_LINE_REST =
  'CHANGE_QUANTITY_PRODUCT_LINE_REST';
export const CHANGE_QUANTITY_PRODUCT_LINE_SUCCESS_REST =
  'CHANGE_QUANTITY_PRODUCT_LINE_SUCCESS_REST';

export const REMOVE_ORDER_LOADING = 'REMOVE_ORDER_LOADING';
export const REMOVE_ORDER_SUCCESS = 'REMOVE_ORDER_SUCCESS';
export const REMOVE_ORDER_ERROR = 'REMOVE_ORDER_ERROR';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_CHANGEQTY_ITEM = 'CART_CHANGEQTY_ITEM';
export const CART_REMOVE_TOTAL = 'CART_REMOVE_TOTAL';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';

export const ORDERS_LIST_REQUEST = 'ORDERS_LIST_REQUEST';
export const ORDERS_LIST_SUCCESS = 'ORDERS_LIST_SUCCESS';
export const ORDERS_LIST_FAIL = 'ORDERS_LIST_FAIL';
