export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_BY_ID_REQUEST = 'PRODUCT_BY_ID_REQUEST';
export const PRODUCT_BY_ID_SUCCESS = 'PRODUCT_BY_ID_SUCCESS';
export const PRODUCT_BY_ID_ERROR = 'PRODUCT_BY_ID_ERROR';

export const SEARCHBAR_SET_KEYWORD = 'SEARCHBAR_SET_KEYWORD';
export const SEARCHBAR_CATEGORY_NAME = 'SEARCHBAR_CATEGORY_NAME';

export const CREATE_ORDER = 'CREATE_ORDER';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const CLEAR_CART = 'CLEAR_CART';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

export const EDIT_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const EDIT_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS ';
export const EDIT_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';

export const REMOVE_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const REMOVE_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS ';
export const REMOVE_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';

export const GET_REVIEW_REQUEST = "GET_REVIEW_REQUEST";
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS"
export const GET_REVIEW_ERROR = "GET_REVIEW_ERROR";

export const ADD_CATEGORY_PRODUCT_REQUEST = 'ADD_CATEGORY_PRODUCT_REQUEST';
export const ADD_CATEGORY_PRODUCT_SUCCESS = 'ADD_CATEGORY_PRODUCT_SUCCESS';
export const ADD_CATEGORY_PRODUCT_FAIL = 'ADD_CATEGORY_PRODUCT_FAIL';

export const REMOVE_CATEGORY_PRODUCT_REQUEST = 'REMOVE_CATEGORY_PRODUCT_REQUEST';
export const REMOVE_CATEGORY_PRODUCT_SUCCESS = 'REMOVE_CATEGORY_PRODUCT_SUCCESS';
export const REMOVE_CATEGORY_PRODUCT_FAIL = 'REMOVE_CATEGORY_PRODUCT_FAIL';


